import AppKit
import CoreServices
import CryptoKit
import UniformTypeIdentifiers

// Clipboard history, the way Windows does it: everything you copy lands in a list,
// click to copy it back, ↩ (or the paste button) to paste it into the front app.
// Text, files and images, plus every screenshot macOS saves. Password managers mark
// their copies as concealed/transient and those are never recorded.

enum ClipKind: String, Codable { case text, image, file }

struct ClipItem: Identifiable, Codable, Equatable {
    var id: UUID
    var kind: ClipKind
    var text: String?          // text: the full text · file: newline-joined paths · image: source path if it came from a file
    var preview: String        // one line, for the row
    var imageFile: String?     // clips/<id>.<ext>
    var hash: String
    var date: Date
    var appBundleID: String?
    var appName: String?
    var pinned: Bool
    var chars: Int
}

@MainActor
final class ClipboardStore: ObservableObject {
    @Published private(set) var items: [ClipItem] = []
    @Published var enabled: Bool { didSet { UserDefaults.standard.set(enabled, forKey: "clipsEnabled") } }
    @Published var hotkeyEnabled: Bool { didSet { UserDefaults.standard.set(hotkeyEnabled, forKey: "clipsHotkey") } }
    // Set by the app delegate when RegisterEventHotKey refuses, which usually means
    // another launcher already owns ⇧⌘V.
    @Published var hotkeyUnavailable = false
    @Published var screenshotsEnabled: Bool { didSet { UserDefaults.standard.set(screenshotsEnabled, forKey: "clipsScreenshots") } }
    @Published var maxItems: Int {
        didSet {
            UserDefaults.standard.set(maxItems, forKey: "clipsMax")
            trim()
            scheduleSave()
        }
    }

    private let pb = NSPasteboard.general
    private var lastCount = -1
    private var timer: Timer?
    private var saveWork: DispatchWorkItem?
    private var thumbs: [UUID: NSImage] = [:]
    private var icons: [String: NSImage] = [:]

    private var shotSource: DispatchSourceFileSystemObject?
    private var shotDir: URL?
    private var shotSeen: Set<String> = []
    private var shotWork: DispatchWorkItem?

    private static let skipTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
    ]
    private static let screenshotBundle = "com.apple.screenshot.launcher"

    init() {
        let d = UserDefaults.standard
        enabled = (d.object(forKey: "clipsEnabled") as? Bool) ?? true
        hotkeyEnabled = (d.object(forKey: "clipsHotkey") as? Bool) ?? true
        screenshotsEnabled = (d.object(forKey: "clipsScreenshots") as? Bool) ?? true
        maxItems = max(20, (d.object(forKey: "clipsMax") as? Int) ?? 150)
    }

    func start() {
        load()
        lastCount = pb.changeCount
        timer = Timer.scheduledTimer(withTimeInterval: 0.35, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.poll() }
        }
        startScreenshotWatch()
    }

    var pinnedCount: Int { items.filter(\.pinned).count }

    // MARK: - Capture

    private func poll() {
        let c = pb.changeCount
        guard c != lastCount else { return }
        lastCount = c
        guard enabled else { return }
        capture()
    }

    private func capture() {
        let types = pb.types ?? []
        if types.contains(where: { Self.skipTypes.contains($0.rawValue) }) { return }
        let app = NSWorkspace.shared.frontmostApplication
        let bundle = app?.bundleIdentifier
        let appName = app?.localizedName

        if let urls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            let paths = urls.map(\.path)
            let joined = paths.joined(separator: "\n")
            let preview = paths.count == 1 ? urls[0].lastPathComponent : "\(paths.count) files · \(urls[0].lastPathComponent), …"
            add(ClipItem(id: UUID(), kind: .file, text: joined, preview: preview, imageFile: nil, hash: Self.sha(Data(joined.utf8)),
                         date: Date(), appBundleID: bundle, appName: appName, pinned: false, chars: paths.count))
            return
        }

        // "Copy image" in a browser ships the picture plus its URL as text; a rich-text
        // copy ships text plus a rendering. The writer lists its preferred type first,
        // so that order decides, and a lone URL never outranks a picture.
        let string = pb.string(forType: .string)?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        let hasImage = pb.canReadItem(withDataConformingToTypes: [UTType.image.identifier])
        let imageIdx = types.firstIndex { UTType($0.rawValue)?.conforms(to: .image) == true } ?? Int.max
        let stringIdx = types.firstIndex { $0 == .string } ?? Int.max
        let preferImage = hasImage && (string.isEmpty || Self.looksLikeURL(string) || imageIdx < stringIdx)
        if preferImage, captureImage(bundle: bundle, appName: appName) { return }

        if !string.isEmpty {
            var text = string
            if text.count > 500_000 { text = String(text.prefix(500_000)) }
            add(ClipItem(id: UUID(), kind: .text, text: text, preview: Self.preview(of: text), imageFile: nil, hash: Self.sha(Data(text.utf8)),
                         date: Date(), appBundleID: bundle, appName: appName, pinned: false, chars: text.count))
            return
        }

        if hasImage { _ = captureImage(bundle: bundle, appName: appName) }
    }

    private func captureImage(bundle: String?, appName: String?) -> Bool {
        guard let image = NSImage(pasteboard: pb),
              let tiff = image.tiffRepresentation,
              let rep = NSBitmapImageRep(data: tiff),
              let png = rep.representation(using: .png, properties: [:]),
              png.count <= 25_000_000 else { return false }
        let hash = Self.sha(png)
        if let idx = items.firstIndex(where: { $0.hash == hash }) { bump(idx, bundle: bundle, appName: appName); return true }
        let id = UUID()
        let file = "clips/\(id.uuidString).png"
        CockpitPaths.ensure()
        CockpitPaths.writePrivate(png, to: CockpitPaths.dir.appendingPathComponent(file))
        add(ClipItem(id: id, kind: .image, text: nil, preview: "Image · \(rep.pixelsWide)×\(rep.pixelsHigh)", imageFile: file, hash: hash,
                     date: Date(), appBundleID: bundle, appName: appName, pinned: false, chars: 0))
        return true
    }

    private func add(_ item: ClipItem) {
        if let idx = items.firstIndex(where: { $0.hash == item.hash }) {
            bump(idx, bundle: item.appBundleID, appName: item.appName)
            return
        }
        items.insert(item, at: 0)
        trim()
        scheduleSave()
    }

    private func bump(_ idx: Int, bundle: String?, appName: String?) {
        var it = items.remove(at: idx)
        it.date = Date()
        if let bundle { it.appBundleID = bundle; it.appName = appName }
        items.insert(it, at: 0)
        scheduleSave()
    }

    private func trim() {
        var unpinned = 0
        var keep: [ClipItem] = []
        for it in items {
            if it.pinned { keep.append(it); continue }
            unpinned += 1
            if unpinned <= maxItems { keep.append(it) } else { removeFile(of: it) }
        }
        if keep.count != items.count { items = keep }
    }

    // MARK: - Screenshots

    // macOS saves screenshots to a folder, not the clipboard. Watch that folder and
    // pull every new one in, so ⇧⌘4 lands in the history like a copy would.
    private static var screenshotDirectory: URL {
        let fm = FileManager.default
        if let loc = UserDefaults(suiteName: "com.apple.screencapture")?.string(forKey: "location") {
            let p = (loc as NSString).expandingTildeInPath
            var isDir: ObjCBool = false
            if fm.fileExists(atPath: p, isDirectory: &isDir), isDir.boolValue { return URL(fileURLWithPath: p) }
        }
        return fm.homeDirectoryForCurrentUser.appendingPathComponent("Desktop")
    }

    private func startScreenshotWatch() {
        let dir = Self.screenshotDirectory
        shotDir = dir
        shotSeen = Set((try? FileManager.default.contentsOfDirectory(atPath: dir.path)) ?? [])
        let fd = open(dir.path, O_EVTONLY)
        guard fd >= 0 else { return }
        let src = DispatchSource.makeFileSystemObjectSource(fileDescriptor: fd, eventMask: [.write, .extend, .rename], queue: .main)
        src.setEventHandler { [weak self] in
            Task { @MainActor in self?.scheduleScreenshotScan() }
        }
        src.setCancelHandler { close(fd) }
        src.resume()
        shotSource = src
    }

    private func scheduleScreenshotScan() {
        shotWork?.cancel()
        let w = DispatchWorkItem { [weak self] in Task { @MainActor in self?.scanScreenshots() } }
        shotWork = w
        DispatchQueue.main.asyncAfter(deadline: .now() + 1.5, execute: w)   // let the file finish writing
    }

    private func scanScreenshots() {
        guard let dir = shotDir, let names = try? FileManager.default.contentsOfDirectory(atPath: dir.path) else { return }
        let exts: Set<String> = ["png", "jpg", "jpeg", "heic", "tiff"]
        for name in names where !shotSeen.contains(name) {
            shotSeen.insert(name)
            guard screenshotsEnabled, !name.hasPrefix("."),
                  exts.contains((name as NSString).pathExtension.lowercased()) else { continue }
            let url = dir.appendingPathComponent(name)
            // macOS names the file in the user's language: "Bildschirmfoto…",
            // "Capture d'écran…", "Снимок экрана…". The English prefix is only a fast
            // path; Spotlight's screen-capture flag is what actually identifies one.
            guard name.lowercased().hasPrefix("screenshot") || Self.isScreenCapture(url) else { continue }
            importScreenshot(url)
        }
    }

    private static func isScreenCapture(_ url: URL) -> Bool {
        guard let item = MDItemCreate(nil, url.path as CFString) else { return false }
        for key in ["kMDItemIsScreenCapture", "kMDItemScreenCaptureType"] {
            guard let value = MDItemCopyAttribute(item, key as CFString) else { continue }
            if let number = value as? NSNumber, number.boolValue { return true }
            if let text = value as? String, !text.isEmpty { return true }
        }
        return false
    }

    private func importScreenshot(_ url: URL) {
        guard let data = try? Data(contentsOf: url), !data.isEmpty, data.count <= 60_000_000 else { return }
        let hash = Self.sha(data)
        if items.contains(where: { $0.hash == hash }) { return }
        let id = UUID()
        let ext = url.pathExtension.isEmpty ? "png" : url.pathExtension.lowercased()
        let file = "clips/\(id.uuidString).\(ext)"
        CockpitPaths.ensure()
        CockpitPaths.writePrivate(data, to: CockpitPaths.dir.appendingPathComponent(file))
        var size = ""
        if let rep = NSBitmapImageRep(data: data) { size = " · \(rep.pixelsWide)×\(rep.pixelsHigh)" }
        add(ClipItem(id: id, kind: .image, text: url.path, preview: url.deletingPathExtension().lastPathComponent + size, imageFile: file, hash: hash,
                     date: Date(), appBundleID: Self.screenshotBundle, appName: "Screenshot", pinned: false, chars: 0))
    }

    // MARK: - Actions

    func copy(_ item: ClipItem) {
        pb.clearContents()
        switch item.kind {
        case .text:
            pb.setString(item.text ?? "", forType: .string)
        case .file:
            let urls = (item.text ?? "").split(separator: "\n").map { URL(fileURLWithPath: String($0)) as NSURL }
            pb.writeObjects(urls)
        case .image:
            // The picture for chats and editors, plus the file for Finder when it still exists.
            var objects: [NSPasteboardWriting] = []
            if let f = item.imageFile, let img = NSImage(contentsOf: CockpitPaths.dir.appendingPathComponent(f)) { objects.append(img) }
            if let p = item.text, FileManager.default.fileExists(atPath: p) { objects.append(URL(fileURLWithPath: p) as NSURL) }
            pb.writeObjects(objects)
        }
        lastCount = pb.changeCount   // our own write, don't re-record it
        if let idx = items.firstIndex(where: { $0.id == item.id }) { bump(idx, bundle: nil, appName: nil) }
    }

    // ⌘V into whatever app is frontmost. Needs Accessibility, which the scroll flip already has.
    static func sendPaste() {
        guard AXIsProcessTrusted() else { return }
        // 9 is V on QWERTY only. On Dvorak or AZERTY that position is a different letter,
        // so the layout in use decides which key to press.
        let key = KeyLayout.virtualKey(for: "v") ?? 9
        let src = CGEventSource(stateID: .combinedSessionState)
        let down = CGEvent(keyboardEventSource: src, virtualKey: key, keyDown: true)
        let up = CGEvent(keyboardEventSource: src, virtualKey: key, keyDown: false)
        down?.flags = .maskCommand
        up?.flags = .maskCommand
        down?.post(tap: .cghidEventTap)
        up?.post(tap: .cghidEventTap)
    }

    func delete(_ item: ClipItem) {
        guard let idx = items.firstIndex(where: { $0.id == item.id }) else { return }
        removeFile(of: items[idx])
        items.remove(at: idx)
        scheduleSave()
    }

    func togglePin(_ item: ClipItem) {
        guard let idx = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[idx].pinned.toggle()
        scheduleSave()
    }

    func clear() {
        for it in items where !it.pinned { removeFile(of: it) }
        items.removeAll { !$0.pinned }
        scheduleSave()
    }

    // MARK: - Images + icons

    func thumb(for item: ClipItem) -> NSImage? {
        guard item.kind == .image, let f = item.imageFile else { return nil }
        if let t = thumbs[item.id] { return t }
        guard let img = NSImage(contentsOf: CockpitPaths.dir.appendingPathComponent(f)) else { return nil }
        let side: CGFloat = 48
        let scale = min(side / max(1, img.size.width), side / max(1, img.size.height), 1)
        let size = NSSize(width: max(1, img.size.width * scale), height: max(1, img.size.height * scale))
        let t = NSImage(size: size)
        t.lockFocus()
        img.draw(in: NSRect(origin: .zero, size: size), from: .zero, operation: .sourceOver, fraction: 1)
        t.unlockFocus()
        thumbs[item.id] = t
        return t
    }

    func icon(for item: ClipItem) -> NSImage? {
        guard let id = item.appBundleID else { return nil }
        if let i = icons[id] { return i }
        var image: NSImage?
        if let running = NSRunningApplication.runningApplications(withBundleIdentifier: id).first, let icon = running.icon {
            image = icon
        } else if let url = NSWorkspace.shared.urlForApplication(withBundleIdentifier: id) {
            image = NSWorkspace.shared.icon(forFile: url.path)
        }
        if let image { icons[id] = image }
        return image
    }

    // MARK: - Persistence

    private func load() {
        guard let data = try? Data(contentsOf: CockpitPaths.clips) else { return }
        let dec = JSONDecoder()
        dec.dateDecodingStrategy = .iso8601
        items = (try? dec.decode([ClipItem].self, from: data)) ?? []
    }

    private func scheduleSave() {
        saveWork?.cancel()
        let work = DispatchWorkItem { [weak self] in Task { @MainActor in self?.save() } }
        saveWork = work
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.5, execute: work)
    }

    private func save() {
        CockpitPaths.ensure()
        let enc = JSONEncoder()
        enc.dateEncodingStrategy = .iso8601
        if let data = try? enc.encode(items) { CockpitPaths.writePrivate(data, to: CockpitPaths.clips) }
    }

    private func removeFile(of item: ClipItem) {
        thumbs[item.id] = nil
        if let f = item.imageFile { try? FileManager.default.removeItem(at: CockpitPaths.dir.appendingPathComponent(f)) }
    }

    private static func sha(_ data: Data) -> String {
        SHA256.hash(data: data).prefix(12).map { String(format: "%02x", $0) }.joined()
    }

    private static func looksLikeURL(_ s: String) -> Bool {
        guard !s.contains(" "), !s.contains("\n") else { return false }
        return s.hasPrefix("http://") || s.hasPrefix("https://") || s.hasPrefix("file://") || s.hasPrefix("data:")
    }

    private static func preview(of text: String) -> String {
        let firstLine = text.split(whereSeparator: \.isNewline).first(where: { !$0.trimmingCharacters(in: .whitespaces).isEmpty }).map(String.init) ?? text
        let collapsed = firstLine.split(whereSeparator: \.isWhitespace).joined(separator: " ")
        return collapsed.count > 160 ? String(collapsed.prefix(160)) + "…" : collapsed
    }
}

extension Array {
    subscript(safe index: Int) -> Element? { indices.contains(index) ? self[index] : nil }
}
